name: vitta
description: "A simple, elegant personal finance tracker android app designed for speed and clarity. Track every Rupee with ease."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - logo/vitta.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "logo/vitta.png"
